# -*- coding: utf-8 -*-
"""Calculate Weekly Pay

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgl1Ets0Bit2qz5jq931CK4QU63xOWc3
"""

#Christopher Kenny
#CS 175
#Calculate Weekly Pay

def get_input():
  wage = float(input("Please enter wage: "))
  hours = float(input("Please enter hours worked: "))
  return wage, hours

def weekly_pay():
    wage, hours = get_input()
    if hours > 40:
      pay = wage * 40
      overtime = hours - 40
      OvertimePay = overtime * (wage * 1.5)
      pay = pay + OvertimePay
      print(f"Weekly pay: ${pay}")
    else:
      pay = wage * hours
      print(f"Weekly pay: ${pay}")

weekly_pay()